version: '3'
services:
  webapp:
   image: llucas/hadi:latest
   ports:
    - '80:80'
    - '4443:443'
   volumes:
    - ./app:/var/www/
    - ./certs:/etc/apache2/certs/hf
   command: /start.sh
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
volumes:
  app:
  db:
  certs: