version: '2'
services:
  webapp:
   image:  llucas/oi:latest
   ports:
    - '80:80'
    - '443:443'
   volumes:
    - ./app:/var/www/
    - ./certs:/etc/apache2/certs/hf
   command: /start.sh
   networks:
      - elk
  mysql:
    image: llucas/mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - elk
  # elasticsearch:
  #   build:
  #     context: elasticsearch/
  #   volumes:
  #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk

  # logstash:
  #   build:
  #     context: logstash/
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch
  # kibana:
  #   build:
  #     context: kibana/
  #   volumes:
  #     - ./kibana/config/:/usr/share/kibana/config:ro
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch
networks:
  elk:
    driver: bridge
volumes:
  app:
  db:
  certs:
  # es-data