version: '2'
services:
  webapp:
   image:  llucas/llucas/oi:latest
   ports:
    - '80:80'
    - '443:443'
   volumes:
    - ./app:/var/www/    
   command: /start.sh
   networks:
      - elk
  mysql:
    image: llucas/mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - elk
networks:
  elk:
    driver: bridge
volumes:
  app:
  db:
  certs:
  # es-data